spring:
  profiles:
    active: development
---
spring:
  profiles: development
  redis:
    host: 192.168.99.100
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.99.101:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
  zipkin:
      base-url: http://zipkin:9411/
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    database: H2
  datasource:
    initialize: false


---
spring:
  profiles: cloud
  zipkin:
      base-url: ${vcap.services.rabbitmq.credentials.uri:http://192.168.11.1:9411}
  rabbitmq:
    host: ${vcap.services.rabbitmq.credentials.uri:192.168.11.1}
    username: ${vcap.services.rabbitmq.credentials.username:user}
    password: ${vcap.services.rabbitmq.credentials.password:pass}
  redis:
      host: ${vcap.services.catalog-redis.credentials.hostname:localhost}
      port: ${vcap.services.catalog-redis.credentials.port:6379}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/

