
logging.level.org.springframework.cloud.sleuth: DEBUG
spring:
  application:
    name: zipkin-sample
---
spring:
  profiles: cloud
  zipkin:
      base-url: ${vcap.services.zipkin-server.credentials.uri:http://host.pcfdev.io:9411}
  rabbitmq:
     host: ${vcap.services.rabbitmq.credentials.hostname:host.pcfdev.io}
     username: ${vcap.services.rabbitmq.credentials.username:user}
     password: ${vcap.services.rabbitmq.credentials.password:pass}

  sleuth:
    sampler:
      percentage: 1
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/

---
server.port: 8081
spring:
  profiles: development
  zipkin:
      base-url: ${vcap.services.zipkin-server.credentials.uri:http://host.pcfdev.io:9411}
  rabbitmq:
    host: ${vcap.services.rabbitmq.credentials.uri:host.pcfdev.io}
    username: ${vcap.services.rabbitmq.credentials.username:user}
    password: ${vcap.services.rabbitmq.credentials.password:pass}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSecond: 3
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
