spring:
  profiles:
    active: development

---
spring:
  profiles: development
  application:
    name: edge-service
  sleuth:
    sampler:
      percentage: 1
    enabled: false
  rabbitmq:
    host: "localhost"
    username: "user"
    password: "pass"
  datasource:
    initialize: false
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    account-service: /account/**
    payment-service: /payment/**
    inventory-service: /inventory/**
    order-service: /order/**
    user-service: /user/**
    catalog-service: /catalog/**
    shopping-cart-service: /shoppingcart/**
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: edge-service
  zipkin:
      base-url: http://zipkin:9411/
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    account-service: /account/**
    payment-service: /payment/**
    inventory-service: /inventory/**
    order-service: /order/**
    user-service: /user/**
    catalog-service: /catalog/**
    shopping-cart-service: /shoppingcart/**
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

---
spring:
  profiles: cloud
  rabbitmq:
    host: ${vcap.services.rabbitmq.credentials.uri:192.168.11.1}
    username: ${vcap.services.rabbitmq.credentials.username:user}
    password: ${vcap.services.rabbitmq.credentials.password:pass}
  datasource:
    initialize: false
  sleuth:
    sampler:
      percentage: 1

zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    account-service: /account/**
    payment-service: /payment/**
    inventory-service: /inventory/**
    order-service: /order/**
    user-service: /user/**
    catalog-service: /catalog/**
    shopping-cart-service: /shoppingcart/**
security:
  oauth2:
    resource:
      userInfoUri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/uaa/user
  ignored: /catalog/**
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/

